# Site settings
title: Eric Dupertuis
email: dupertuis.eric@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edupertuis.net" # the base hostname & protocol for your site

highlighter: pygments
markdown: kramdown

paginate: 5