name:               "Eric"
baseurl:            ""
permalink:          /:year/:month/:day/:title.html
markdown:           kramdown
nav:
  - name:           "About"
    href:           "/about"
sass:
  style:            :compressed
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
